const APPLIED_COLUMN_TITLE = "Applied";
const INTERVIEW_COLUMN_TITLE = "Interview";
const IN_PROGRESS_COLUMN_TITLE = "In Progress";
const OFFER_COLUMN_TITLE = "Offer";

export {
    APPLIED_COLUMN_TITLE,
    INTERVIEW_COLUMN_TITLE,
    IN_PROGRESS_COLUMN_TITLE,
    OFFER_COLUMN_TITLE,
};